//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Data/Input/Default.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Default"",
    ""maps"": [
        {
            ""name"": ""1-Seat-Flight"",
            ""id"": ""9b9adfba-ed72-45ec-85c2-5ec0906cbbcc"",
            ""actions"": [
                {
                    ""name"": ""Joystick"",
                    ""type"": ""Value"",
                    ""id"": ""e85ccf71-19f0-439b-ac8e-db80cf8d2509"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""75adaefd-e9ba-4cc7-8403-9cd567e0f6bb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""241fd910-78f2-4c57-b80a-dd8a61406772"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerBalance"",
                    ""type"": ""Button"",
                    ""id"": ""4412bee1-1587-46c8-b7fe-927ddf089f87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerIncreaseEngineSystem"",
                    ""type"": ""Button"",
                    ""id"": ""6c1a67e2-481d-4e5d-85f6-a06c1d868285"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerIncreaseShieldSystem"",
                    ""type"": ""Button"",
                    ""id"": ""c95da7b8-4aa0-41e1-8758-c56e74edf6a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerIncreaseWeaponSystem"",
                    ""type"": ""Button"",
                    ""id"": ""75e97051-f9ba-4c2a-822b-26f2b778cb68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirePrimary"",
                    ""type"": ""Button"",
                    ""id"": ""358de82e-2980-4f07-b14c-e70bd9f07709"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LevelOut"",
                    ""type"": ""Button"",
                    ""id"": ""3a0c764f-f239-4c9d-ab7d-004bf04c767c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c2eb8895-7999-457a-bf8d-9534b5a75b1c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0e6316d2-0352-4712-84b5-8f78d725f407"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""148b6bb0-89ae-4cd8-a5b8-0bff465383d2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f10774ed-04d0-4a23-b14c-3b61720a103f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dbaf0322-39f3-447c-ac68-3bd6472d5223"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""53a0a54d-3f97-4d7f-be1e-2b752e0ae4fe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d6e2f21a-bdad-41b7-8912-e748f3b90d2d"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f49ba318-9b1d-472d-93e0-fb8734aebbcd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""04c10d91-c64d-45cb-a9c3-345d95abc18e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""faf59071-cfba-4b92-ae34-0b3a0622737f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4da9d87b-d2aa-4d03-899b-65f54eeef08e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7b1a013e-f12d-4b23-9f40-465e1956af9f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""57ee0a77-0659-4fc7-ad57-1ebc9fb75cb7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""294a4f29-637c-426f-a709-4544d09c6967"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4183186e-e1a6-4651-b8ef-825726e22253"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerBalance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0fcb972-91cc-42c4-a556-c8662ee3a16f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerIncreaseEngineSystem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd464209-47ea-4eba-a81a-74e2c48bd50f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerIncreaseShieldSystem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c577bbf4-65de-4101-ba2c-b2e9d8028d0b"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerIncreaseWeaponSystem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbd15ba4-1b8c-4c9f-a0e6-77a6f16dcff2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirePrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""260f5a6f-5c97-4bb4-a28c-741f6cea93dc"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LevelOut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""baa84e6c-4f6b-43e0-bd69-cfa2e7c90141"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LevelOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e184fc38-901e-4ca1-8a30-e4d7aa4545b8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LevelOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // 1-Seat-Flight
            m__1SeatFlight = asset.FindActionMap("1-Seat-Flight", throwIfNotFound: true);
            m__1SeatFlight_Joystick = m__1SeatFlight.FindAction("Joystick", throwIfNotFound: true);
            m__1SeatFlight_Throttle = m__1SeatFlight.FindAction("Throttle", throwIfNotFound: true);
            m__1SeatFlight_Boost = m__1SeatFlight.FindAction("Boost", throwIfNotFound: true);
            m__1SeatFlight_PowerBalance = m__1SeatFlight.FindAction("PowerBalance", throwIfNotFound: true);
            m__1SeatFlight_PowerIncreaseEngineSystem = m__1SeatFlight.FindAction("PowerIncreaseEngineSystem", throwIfNotFound: true);
            m__1SeatFlight_PowerIncreaseShieldSystem = m__1SeatFlight.FindAction("PowerIncreaseShieldSystem", throwIfNotFound: true);
            m__1SeatFlight_PowerIncreaseWeaponSystem = m__1SeatFlight.FindAction("PowerIncreaseWeaponSystem", throwIfNotFound: true);
            m__1SeatFlight_FirePrimary = m__1SeatFlight.FindAction("FirePrimary", throwIfNotFound: true);
            m__1SeatFlight_LevelOut = m__1SeatFlight.FindAction("LevelOut", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // 1-Seat-Flight
        private readonly InputActionMap m__1SeatFlight;
        private I_1SeatFlightActions m__1SeatFlightActionsCallbackInterface;
        private readonly InputAction m__1SeatFlight_Joystick;
        private readonly InputAction m__1SeatFlight_Throttle;
        private readonly InputAction m__1SeatFlight_Boost;
        private readonly InputAction m__1SeatFlight_PowerBalance;
        private readonly InputAction m__1SeatFlight_PowerIncreaseEngineSystem;
        private readonly InputAction m__1SeatFlight_PowerIncreaseShieldSystem;
        private readonly InputAction m__1SeatFlight_PowerIncreaseWeaponSystem;
        private readonly InputAction m__1SeatFlight_FirePrimary;
        private readonly InputAction m__1SeatFlight_LevelOut;
        public struct _1SeatFlightActions
        {
            private @InputActions m_Wrapper;
            public _1SeatFlightActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Joystick => m_Wrapper.m__1SeatFlight_Joystick;
            public InputAction @Throttle => m_Wrapper.m__1SeatFlight_Throttle;
            public InputAction @Boost => m_Wrapper.m__1SeatFlight_Boost;
            public InputAction @PowerBalance => m_Wrapper.m__1SeatFlight_PowerBalance;
            public InputAction @PowerIncreaseEngineSystem => m_Wrapper.m__1SeatFlight_PowerIncreaseEngineSystem;
            public InputAction @PowerIncreaseShieldSystem => m_Wrapper.m__1SeatFlight_PowerIncreaseShieldSystem;
            public InputAction @PowerIncreaseWeaponSystem => m_Wrapper.m__1SeatFlight_PowerIncreaseWeaponSystem;
            public InputAction @FirePrimary => m_Wrapper.m__1SeatFlight_FirePrimary;
            public InputAction @LevelOut => m_Wrapper.m__1SeatFlight_LevelOut;
            public InputActionMap Get() { return m_Wrapper.m__1SeatFlight; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(_1SeatFlightActions set) { return set.Get(); }
            public void SetCallbacks(I_1SeatFlightActions instance)
            {
                if (m_Wrapper.m__1SeatFlightActionsCallbackInterface != null)
                {
                    @Joystick.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnJoystick;
                    @Joystick.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnJoystick;
                    @Joystick.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnJoystick;
                    @Throttle.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnThrottle;
                    @Throttle.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnThrottle;
                    @Throttle.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnThrottle;
                    @Boost.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnBoost;
                    @Boost.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnBoost;
                    @Boost.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnBoost;
                    @PowerBalance.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerBalance;
                    @PowerBalance.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerBalance;
                    @PowerBalance.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerBalance;
                    @PowerIncreaseEngineSystem.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseEngineSystem;
                    @PowerIncreaseEngineSystem.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseEngineSystem;
                    @PowerIncreaseEngineSystem.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseEngineSystem;
                    @PowerIncreaseShieldSystem.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseShieldSystem;
                    @PowerIncreaseShieldSystem.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseShieldSystem;
                    @PowerIncreaseShieldSystem.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseShieldSystem;
                    @PowerIncreaseWeaponSystem.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseWeaponSystem;
                    @PowerIncreaseWeaponSystem.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseWeaponSystem;
                    @PowerIncreaseWeaponSystem.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnPowerIncreaseWeaponSystem;
                    @FirePrimary.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnFirePrimary;
                    @FirePrimary.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnFirePrimary;
                    @FirePrimary.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnFirePrimary;
                    @LevelOut.started -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnLevelOut;
                    @LevelOut.performed -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnLevelOut;
                    @LevelOut.canceled -= m_Wrapper.m__1SeatFlightActionsCallbackInterface.OnLevelOut;
                }
                m_Wrapper.m__1SeatFlightActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Joystick.started += instance.OnJoystick;
                    @Joystick.performed += instance.OnJoystick;
                    @Joystick.canceled += instance.OnJoystick;
                    @Throttle.started += instance.OnThrottle;
                    @Throttle.performed += instance.OnThrottle;
                    @Throttle.canceled += instance.OnThrottle;
                    @Boost.started += instance.OnBoost;
                    @Boost.performed += instance.OnBoost;
                    @Boost.canceled += instance.OnBoost;
                    @PowerBalance.started += instance.OnPowerBalance;
                    @PowerBalance.performed += instance.OnPowerBalance;
                    @PowerBalance.canceled += instance.OnPowerBalance;
                    @PowerIncreaseEngineSystem.started += instance.OnPowerIncreaseEngineSystem;
                    @PowerIncreaseEngineSystem.performed += instance.OnPowerIncreaseEngineSystem;
                    @PowerIncreaseEngineSystem.canceled += instance.OnPowerIncreaseEngineSystem;
                    @PowerIncreaseShieldSystem.started += instance.OnPowerIncreaseShieldSystem;
                    @PowerIncreaseShieldSystem.performed += instance.OnPowerIncreaseShieldSystem;
                    @PowerIncreaseShieldSystem.canceled += instance.OnPowerIncreaseShieldSystem;
                    @PowerIncreaseWeaponSystem.started += instance.OnPowerIncreaseWeaponSystem;
                    @PowerIncreaseWeaponSystem.performed += instance.OnPowerIncreaseWeaponSystem;
                    @PowerIncreaseWeaponSystem.canceled += instance.OnPowerIncreaseWeaponSystem;
                    @FirePrimary.started += instance.OnFirePrimary;
                    @FirePrimary.performed += instance.OnFirePrimary;
                    @FirePrimary.canceled += instance.OnFirePrimary;
                    @LevelOut.started += instance.OnLevelOut;
                    @LevelOut.performed += instance.OnLevelOut;
                    @LevelOut.canceled += instance.OnLevelOut;
                }
            }
        }
        public _1SeatFlightActions @_1SeatFlight => new _1SeatFlightActions(this);
        public interface I_1SeatFlightActions
        {
            void OnJoystick(InputAction.CallbackContext context);
            void OnThrottle(InputAction.CallbackContext context);
            void OnBoost(InputAction.CallbackContext context);
            void OnPowerBalance(InputAction.CallbackContext context);
            void OnPowerIncreaseEngineSystem(InputAction.CallbackContext context);
            void OnPowerIncreaseShieldSystem(InputAction.CallbackContext context);
            void OnPowerIncreaseWeaponSystem(InputAction.CallbackContext context);
            void OnFirePrimary(InputAction.CallbackContext context);
            void OnLevelOut(InputAction.CallbackContext context);
        }
    }
}
